version: "3"
services:
  webservice:
    image: aws-amplify-auth
    container_name: "aws-amplify-auth"
    build:
      context: .
      target: aws-amplify-auth
    environment:
      - NODE_ENV=production
    ports:
      - 10000:10000
    stdin_open: true
